development:
  environment:        <%= ENV["PUNTOPAGOS_ENV"]%>
  puntopagos_key:     <%= ENV["PUNTOPAGOS_KEY"]%>
  puntopagos_secret:  <%= ENV["PUNTOPAGOS_SECRET"]%>
test:
  environment:        <%= ENV["PUNTOPAGOS_ENV_TEST"]%>
  puntopagos_key:     <%= ENV["PUNTOPAGOS_KEY_TEST"]%>
  puntopagos_secret:  <%= ENV["PUNTOPAGOS_SECRET_TEST"]%>
production:
  environment:        <%= ENV["PUNTOPAGOS_ENV"]%>
  puntopagos_key:     <%= ENV["PUNTOPAGOS_KEY"]%>
  puntopagos_secret:  <%= ENV["PUNTOPAGOS_SECRET"]%>
