development:
  environment:        "sandbox"
  puntopagos_key:     "ftRi6ioOfOFVF1aJR68J"
  puntopagos_secret:  "vEc6TL3tqpeqXI45sP9L3c4ATMwMGHaIvLxRIeZ7"

test:
  environment:        "sandbox"
  puntopagos_key:     "ftRi6ioOfOFVF1aJR68J"
  puntopagos_secret:  "vEc6TL3tqpeqXI45sP9L3c4ATMwMGHaIvLxRIeZ7"

production:
  environment:        "sandbox"
  puntopagos_key:     "ftRi6ioOfOFVF1aJR68J"
  puntopagos_secret:  "vEc6TL3tqpeqXI45sP9L3c4ATMwMGHaIvLxRIeZ7"
